# 음료수 얼려먹기

In [3]:
import numpy as np

In [ ]:
# # 초기 그래프
# [[0, 0, 1, 1, 0],
#  [0, 0, 0, 1, 1],
#  [1, 1, 1, 1, 1],
#  [0, 0, 0, 0, 0]]


# # ice_dfs(0,0) -> 시작 iter 0
# [[1, 0, 1, 1, 0],
#  [0, 0, 0, 1, 1],
#  [1, 1, 1, 1, 1],
#  [0, 0, 0, 0, 0]]

# #ice_dfs(0,1) -> 우 recur 1
# [[1, 1, 1, 1, 0],
#  [0, 0, 0, 1, 1],
#  [1, 1, 1, 1, 1],
#  [0, 0, 0, 0, 0]]

# #ice_dfs(1,1) -> 하 recur 2
# [[1, 1, 1, 1, 0],
#  [0, 1, 0, 1, 1],
#  [1, 1, 1, 1, 1],
#  [0, 0, 0, 0, 0]]

# #ice_dfs(1,0) -> 좌 recur 3
# [[1, 1, 1, 1, 0],
#  [1, 1, 0, 1, 1],
#  [1, 1, 1, 1, 1],
#  [0, 0, 0, 0, 0]]

# True # recur 3 종료

# #ice_dfs(1,2) -> (recur2에서) 우 recur 4
# [[1, 1, 1, 1, 0],
#  [1, 1, 1, 1, 1],
#  [1, 1, 1, 1, 1],
#  [0, 0, 0, 0, 0]]

# True # recur 4 종료
# True # recur 2 종료
# True # recur 1 종료
# True # recur 0 종료

- DFS는 stack 구조로 First Input의 결과가 하위 재귀호출이 끝난 후에 반환됨을 기억해야함
- 여기서는 위에서 정의한 return 값이 헷갈렸음
- 즉, 다시 이해해보면
- 0,0에서 시작하면 성공조건을 타고 상하좌우에 대해 각각 재귀호출에 들어간다.
- 방문처리가 되면서 하위 호출들이 모두 종료조건에 걸림
- (우->하->(좌),(우))
- 다시 타고 올라오면서 True값을 return하지만 값은 최종값인 1개만 리턴
- 시작점인 (0,0)에 대해서 재귀호출을 하는 세부적인 사항은 아래와 같다.

In [5]:
n, m = map(int, input().split())

graph = []
for i in range(n):
    graph.append(list(map(int, input()))) # 전체 맵 상태를 입력받는곳 중요
print(graph)

def dfs(x, y):
    if x <= -1 or x >= n or y <= -1 or y >= m:
        return False
    if graph[x][y] == 0: # 요기부터 -->
        graph[x][y] = 1
        
        dfs(x - 1, y)    
        dfs(x, y - 1)
        dfs(x + 1, y)
        dfs(x, y + 1)
        
        return True
    return False # --> 요기까지 0을 1로 채워가면서 한 섹터를 채울때마다 True를 반환

result = 0
for i in range (n):
    for j in range (m):
        if dfs(i, j) == True:
            result += 1
            print(result)

[[0, 0, 1, 1, 0], [0, 0, 0, 1, 1], [1, 1, 1, 1, 1], [0, 0, 0, 0, 0]]
[[1 1 1 1 0]
 [1 1 0 1 1]
 [1 1 1 1 1]
 [0 0 0 0 0]]
[[1 1 1 1 0]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [0 0 0 0 0]]
[[1 1 1 1 0]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [0 0 0 0 0]]
[[1 1 1 1 0]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [0 0 0 0 0]]
[[1 1 1 1 0]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [0 0 0 0 0]]
1
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [0 0 0 0 0]]
2
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
3


In [9]:
n, m = map(int, input().split())

graph = []
for i in range(n):
    graph.append(list(map(int, input())))
print(graph)

def dfs(x, y):
    if x <= -1 or x >= n or y <= -1 or y >= m:
        return False
    if graph[x][y] == 0:
        graph[x][y] = 1
        
    while True:
        x -= 1
        if x <= -1 or x >= n or y <= -1 or y >= m:
            continue
        if graph[x][y] == 0:
            graph[x][y] = 1
    while True:
        x += 1
        if x <= -1 or x >= n or y <= -1 or y >= m:
            break
        if graph[x][y] == 0:
            graph[x][y] = 1
    while True:
        y -= 1
        if x <= -1 or x >= n or y <= -1 or y >= m:
            break
        if graph[x][y] == 0:
            graph[x][y] = 1
    while True:
        y += 1
        if x <= -1 or x >= n or y <= -1 or y >= m:
            break
        if graph[x][y] == 0:
            graph[x][y] = 1
        
        print(np.array(graph))
        return True
    return False

result = 0
for i in range (n):
    for j in range (m):
        if dfs(i, j) == True:
            result += 1
            print(result)

[[0, 0, 1, 1, 0], [0, 0, 0, 1, 1], [1, 1, 1, 1, 1], [0, 0, 0, 0, 0]]
